using System.IO.Compression;
using System.Reflection;
using System.Text.Encodings.Web;
using System.Text.Json;

namespace ChatToDashboard.Api.Integrations;

/// <summary>
/// Generates the three self-contained deliverables handed to a client. Deliverables 1 and 2
/// (Part D and Part E) are single HTML files with their own config baked in at generation time
/// (read/directory/permissions API URLs, the confirmed identity-transport mechanism, the
/// visual-identity tokens) — nothing in either one calls back to our own backend at view-time,
/// per Part D/E's "no dependency on our systems at view-time" requirement. Deliverable 3 is the
/// connector microservice source (../IntegrationConnector, embedded into this assembly — see
/// this project's .csproj) that the client builds and deploys themselves, pre-filled with
/// whatever of its config this integration's settings already answer.
///
/// Widget rendering (Deliverables 1/2) covers the five core types (kpi/bar/line/pie/table) via
/// Chart.js from a CDN — a deliberate, documented scope choice: reproducing every specialized
/// widget type this app's own design system has (progress-table/trend-matrix/status-bar/radial-
/// gauge/linear-gauge) inside a hand-generated single file would be its own multi-week effort;
/// an unrecognized type falls back to a plain key/value table so nothing silently disappears.
/// </summary>
public class IntegrationDeliverables
{
    public string BuildViewerHtml(ExternalIntegration integration)
    {
        var tokens = ResolveTokens(integration);
        var config = new
        {
            readApiBaseUrl = integration.DashboardsUrl ?? "",
            identity = new
            {
                mechanism = integration.IdentityConfirmed ? integration.IdentityMechanism : null,
                parameterName = integration.IdentityConfirmed ? integration.IdentityParameterName : null,
            },
            accent = tokens.Accent,
            secondary = tokens.Secondary,
            font = tokens.Font,
            integrationName = integration.Name,
        };
        var configJson = JsonSerializer.Serialize(config, new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping });
        // Inlined, never fetched — a client's network may allow nothing but its own domains
        // (this stopped an actual deployment cold: the CDN request was blocked outright), and
        // this file is meant to work inside exactly that kind of locked-down network.
        // Defensive: a literal "</script" inside the embedded JS would close the tag early as
        // far as the HTML parser is concerned, regardless of it being inside a JS string — none
        // in the vendored 4.4.4 build today, but this guards a future version bump too.
        var chartJs = ReadEmbeddedText("vendor.chart.umd.js").Replace("</script", "<\\/script", StringComparison.OrdinalIgnoreCase);

        return $$"""
        <!doctype html>
        <html lang="ar" dir="rtl">
        <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>لوحات المتابعة</title>
        <meta name="x-integration-name" content="{{Escape(integration.Name)}}" />
        <!--
          Generated by غرفة القيادة — see the integration name in the meta tag just above (never
          put inside this comment itself: an integration name containing "--" would prematurely
          close an HTML comment under the stricter SGML-style comment rule several non-browser
          HTML parsers/sanitizers still follow, corrupting everything after it).
          Fully self-contained: Chart.js (for bar/line/pie rendering) is embedded below, never
          fetched from anywhere. No dependency on غرفة القيادة's own systems at view-time either —
          every data call below goes to READ_API_BASE_URL only, which you host.
          Regenerate this file from غرفة القيادة after changing the read API URL, the identity-
          transport mechanism, or the visual identity — it is not fetched or updated remotely.
        -->
        <script>{{chartJs}}</script>
        <style>
        {{BaseCss(tokens)}}
        .tabbar{display:flex;gap:6px;flex-wrap:wrap;padding:14px 18px;border-bottom:1px solid var(--grid);overflow-x:auto}
        .tab{padding:8px 16px;border:1px solid var(--grid);border-radius:999px;background:var(--surface);
          color:var(--ink-2);font-size:13px;font-weight:600;cursor:pointer;white-space:nowrap}
        .tab.active{background:var(--accent-soft);color:var(--accent);border-color:var(--accent)}
        .content{padding:18px}
        .dash-summary{margin:0 0 16px;color:var(--ink-2);font-size:14px;line-height:1.7}
        .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}
        .widget{position:relative;background:var(--surface);border:1px solid var(--grid);border-radius:14px;padding:16px}
        .widget h3{margin:0 0 10px;font-size:13px;font-weight:700;color:var(--ink-2)}
        .widget.kpi{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;min-height:120px}
        .kpi-value{font-size:30px;font-weight:800;color:var(--accent)}
        table.data-table{width:100%;border-collapse:collapse;font-size:13px}
        table.data-table th,table.data-table td{padding:7px 9px;border-bottom:1px solid var(--grid);text-align:start}
        table.data-table th{color:var(--ink-2);font-weight:700}
        .src-btn{position:absolute;top:12px;inset-inline-start:12px;width:20px;height:20px;border:1px solid var(--accent);
          border-radius:50%;background:var(--accent-soft);color:var(--accent);font-size:11px;cursor:pointer;padding:0}
        .src-pop{display:none;position:absolute;top:38px;inset-inline-start:12px;z-index:20;width:min(280px,85%);
          background:var(--surface);border:1px solid var(--grid);border-radius:10px;box-shadow:0 8px 24px rgba(0,0,0,.15);
          padding:10px 12px;font-size:12px;line-height:1.7;color:var(--ink-2)}
        .src-pop.open{display:block}
        .state-msg{padding:40px;text-align:center;color:var(--ink-2)}
        canvas{max-height:240px}
        </style>
        </head>
        <body>
        <div id="tabbar" class="tabbar"></div>
        <div id="content" class="content"><div class="state-msg">جارٍ التحميل…</div></div>
        <script>
        const CONFIG = {{configJson}};
        const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

        {{IdentityTransportJs}}

        let dashboards = [];
        let activeId = null;
        const chartInstances = [];

        async function init() {
          if (!CONFIG.readApiBaseUrl) {
            document.getElementById('content').innerHTML = '<div class="state-msg">لم يتم ضبط نقطة القراءة (Read API) لهذا التكامل بعد.</div>';
            return;
          }
          try {
            const res = await fetchWithIdentity(CONFIG.readApiBaseUrl);
            if (!res.ok) throw new Error('HTTP ' + res.status);
            dashboards = await res.json();
            if (!Array.isArray(dashboards)) dashboards = dashboards.dashboards || [];
          } catch (err) {
            document.getElementById('content').innerHTML = '<div class="state-msg">تعذّر تحميل قائمة اللوحات: ' + esc(err.message) + '</div>';
            return;
          }
          if (dashboards.length === 0) {
            document.getElementById('content').innerHTML = '<div class="state-msg">لا توجد لوحات متاحة لك حاليًا.</div>';
            return;
          }
          renderTabs();
          openDashboard(dashboards[0].dashboardId || dashboards[0].id);
        }

        function renderTabs() {
          const bar = document.getElementById('tabbar');
          bar.innerHTML = dashboards.map(d => {
            const id = d.dashboardId || d.id;
            return '<button type="button" class="tab' + (id === activeId ? ' active' : '') + '" data-id="' + esc(id) + '">' + esc(d.title || id) + '</button>';
          }).join('');
          bar.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => openDashboard(btn.dataset.id)));
        }

        async function openDashboard(id) {
          activeId = id;
          renderTabs();
          const content = document.getElementById('content');
          content.innerHTML = '<div class="state-msg">جارٍ التحميل…</div>';
          chartInstances.forEach(c => c.destroy());
          chartInstances.length = 0;
          try {
            const url = CONFIG.readApiBaseUrl.replace(/\/$/, '') + '/' + encodeURIComponent(id);
            const res = await fetchWithIdentity(url);
            if (!res.ok) throw new Error('HTTP ' + res.status);
            const dashboard = await res.json();
            renderDashboard(dashboard);
          } catch (err) {
            content.innerHTML = '<div class="state-msg">تعذّر تحميل هذه اللوحة: ' + esc(err.message) + '</div>';
          }
        }

        function renderDashboard(d) {
          const content = document.getElementById('content');
          const summary = d.summary ? '<p class="dash-summary">' + esc(d.summary) + '</p>' : '';
          content.innerHTML = summary + '<div class="grid" id="widget-grid"></div>';
          const grid = document.getElementById('widget-grid');
          (d.widgets || []).forEach((w, i) => grid.appendChild(buildWidget(w, i)));
        }

        function buildWidget(w, index) {
          const card = document.createElement('div');
          card.className = 'widget ' + esc(w.type || '');
          const canConvertSource = !!w.source;
          card.innerHTML =
            (canConvertSource ? '<button type="button" class="src-btn" data-i="' + index + '">ⓘ</button>' +
              '<div class="src-pop" id="src-pop-' + index + '">' + esc(w.source) + '</div>' : '') +
            '<h3>' + esc(w.title || '') + '</h3>' +
            '<div class="widget-body" id="widget-body-' + index + '"></div>';

          const body = card.querySelector('.widget-body');
          renderWidgetBody(body, w, index);

          const srcBtn = card.querySelector('.src-btn');
          if (srcBtn) srcBtn.addEventListener('click', e => {
            e.stopPropagation();
            document.querySelectorAll('.src-pop.open').forEach(p => p.classList.remove('open'));
            document.getElementById('src-pop-' + index).classList.add('open');
          });
          return card;
        }

        function renderWidgetBody(body, w, index) {
          const type = (w.type || '').toLowerCase();
          const data = Array.isArray(w.data) ? w.data : (w.data ? [w.data] : []);
          if (type === 'kpi') {
            // The retargeted query's result column is never guaranteed to be named "value" —
            // it's whatever name the client's own schema (or the retargeting step) gave it — so
            // fall back to the first column of the first row, same "just take what's there"
            // approach the bar/line/pie x/yKey fallback below uses.
            const row0 = data[0] || {};
            const value = ('value' in row0) ? row0.value : (Object.values(row0)[0] ?? w.value ?? '—');
            body.innerHTML = '<div class="kpi-value">' + esc(value) + '</div>';
            return;
          }
          if (type === 'table') {
            body.appendChild(buildTable(data));
            return;
          }
          if ((type === 'bar' || type === 'line' || type === 'pie') && window.Chart && data.length) {
            const canvas = document.createElement('canvas');
            body.appendChild(canvas);
            const xKey = w.xKey || Object.keys(data[0]).find(k => typeof data[0][k] === 'string') || Object.keys(data[0])[0];
            const yKey = w.yKey || Object.keys(data[0]).find(k => typeof data[0][k] === 'number') || Object.keys(data[0])[1];
            const labels = data.map(r => r[xKey]);
            const values = data.map(r => Number(r[yKey]) || 0);
            const chart = new Chart(canvas, {
              type: type === 'pie' ? 'pie' : type,
              data: { labels, datasets: [{ label: w.title || '', data: values,
                backgroundColor: type === 'pie' ? PIE_COLORS(values.length) : CONFIG.accent,
                borderColor: CONFIG.accent, borderWidth: type === 'line' ? 2 : 1 }] },
              options: { responsive: true, plugins: { legend: { display: type === 'pie' } } },
            });
            chartInstances.push(chart);
            return;
          }
          // Unrecognized/specialized widget type — graceful fallback so nothing disappears silently.
          body.appendChild(buildTable(data));
        }

        function buildTable(rows) {
          const table = document.createElement('table');
          table.className = 'data-table';
          if (!rows.length) { table.innerHTML = '<tbody><tr><td>لا توجد بيانات.</td></tr></tbody>'; return table; }
          const keys = Object.keys(rows[0]);
          table.innerHTML =
            '<thead><tr>' + keys.map(k => '<th>' + esc(k) + '</th>').join('') + '</tr></thead>' +
            '<tbody>' + rows.map(r => '<tr>' + keys.map(k => '<td>' + esc(r[k]) + '</td>').join('') + '</tr>').join('') + '</tbody>';
          return table;
        }

        function PIE_COLORS(n) {
          const base = [CONFIG.accent, CONFIG.secondary, '#94A3B8', '#F2B84B', '#22C55E', '#EF6461'];
          const out = [];
          for (let i = 0; i < n; i++) out.push(base[i % base.length]);
          return out;
        }

        document.addEventListener('click', () => document.querySelectorAll('.src-pop.open').forEach(p => p.classList.remove('open')));
        init();
        </script>
        </body>
        </html>
        """;
    }

    public string BuildPermissionsAdminHtml(ExternalIntegration integration)
    {
        var tokens = ResolveTokens(integration);
        var config = new
        {
            readApiBaseUrl = integration.DashboardsUrl ?? "",
            directoryApiUrl = integration.DirectoryUrl ?? "",
            permissionsApiUrl = integration.PermissionsUrl ?? "",
            identity = new
            {
                mechanism = integration.IdentityConfirmed ? integration.IdentityMechanism : null,
                parameterName = integration.IdentityConfirmed ? integration.IdentityParameterName : null,
            },
            accent = tokens.Accent,
            secondary = tokens.Secondary,
            font = tokens.Font,
        };
        var configJson = JsonSerializer.Serialize(config, new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping });

        return $$"""
        <!doctype html>
        <html lang="ar" dir="rtl">
        <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>صلاحيات لوحات المتابعة</title>
        <meta name="x-integration-name" content="{{Escape(integration.Name)}}" />
        <!--
          Generated by غرفة القيادة — see the integration name in the meta tag just above (never
          put inside this comment itself: an integration name containing "--" would prematurely
          close an HTML comment under the stricter SGML-style comment rule several non-browser
          HTML parsers/sanitizers still follow, corrupting everything after it). Admin-only page:
          give access only to whoever on your side should manage dashboard visibility (Part 6 of
          the requirements doc — entirely your own decision, this file enforces none of that
          access itself). Writes permission decisions to PERMISSIONS_API_URL only; never talks to
          غرفة القيادة at view-time.
        -->
        <style>
        {{BaseCss(tokens)}}
        .content{padding:20px;max-width:820px;margin:0 auto}
        h1{font-size:18px;margin:0 0 18px}
        .dash-row{background:var(--surface);border:1px solid var(--grid);border-radius:14px;padding:16px;margin-bottom:14px}
        .dash-row-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}
        .dash-title{font-weight:700;font-size:14px}
        .toggle-group{display:flex;gap:6px;border:1px solid var(--grid);border-radius:999px;padding:3px}
        .toggle-btn{padding:5px 14px;border:0;border-radius:999px;background:transparent;color:var(--ink-2);font-size:12px;font-weight:600;cursor:pointer}
        .toggle-btn.active{background:var(--accent);color:#fff}
        .restricted-panel{margin-top:12px;display:none}
        .restricted-panel.open{display:block}
        .chip-list{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px}
        .chip{display:inline-flex;align-items:center;gap:6px;padding:4px 10px;border-radius:999px;background:var(--accent-soft);color:var(--accent);font-size:12px}
        .chip button{border:0;background:transparent;color:inherit;cursor:pointer;font-size:12px;padding:0}
        .search-row{position:relative}
        .search-row input{width:100%;box-sizing:border-box;padding:8px 12px;border:1px solid var(--grid);border-radius:9px;font-size:13px}
        .suggestions{position:absolute;z-index:10;top:100%;inset-inline-start:0;right:0;background:var(--surface);
          border:1px solid var(--grid);border-radius:9px;margin-top:4px;max-height:200px;overflow-y:auto;box-shadow:0 8px 24px rgba(0,0,0,.12)}
        .suggestion-item{padding:8px 12px;font-size:13px;cursor:pointer;display:flex;justify-content:space-between}
        .suggestion-item:hover{background:var(--accent-soft)}
        .suggestion-tag{font-size:11px;color:var(--ink-2)}
        .empty-warning{margin-top:10px;padding:8px 12px;border-radius:9px;background:rgba(239,100,97,.12);color:#B91C1C;font-size:12px}
        .save-note{font-size:11px;color:var(--ink-2);margin-inline-start:8px}
        .state-msg{padding:40px;text-align:center;color:var(--ink-2)}
        </style>
        </head>
        <body>
        <div class="content">
        <h1>صلاحيات لوحات المتابعة</h1>
        <div id="list"><div class="state-msg">جارٍ التحميل…</div></div>
        </div>
        <script>
        const CONFIG = {{configJson}};
        const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

        {{IdentityTransportJs}}

        let dashboards = [];
        // In-memory per-dashboard state: { mode: 'everyone'|'restricted', allowed: [{id,label,kind}] }
        const state = {};

        async function init() {
          if (!CONFIG.readApiBaseUrl) {
            document.getElementById('list').innerHTML = '<div class="state-msg">لم يتم ضبط نقطة القراءة (Read API) لهذا التكامل بعد.</div>';
            return;
          }
          try {
            // Calls the exact same read endpoint viewer.html does, with the exact same identity
            // mechanism — your connector must recognize the identity this admin session sends as
            // one of its own configured AdminIdentifiers, or any dashboard this page restricts
            // without also allow-listing that identity disappears from this very list on the
            // next load. See the connector's own README (ConnectorOptions.AdminIdentifiers).
            const res = await fetchWithIdentity(CONFIG.readApiBaseUrl);
            if (!res.ok) throw new Error('HTTP ' + res.status);
            let body = await res.json();
            dashboards = Array.isArray(body) ? body : (body.dashboards || []);
          } catch (err) {
            document.getElementById('list').innerHTML = '<div class="state-msg">تعذّر تحميل قائمة اللوحات: ' + esc(err.message) + '</div>';
            return;
          }
          dashboards.forEach(d => {
            const id = d.dashboardId || d.id;
            state[id] = { mode: d.permissionMode || 'everyone', allowed: d.allowedIdentifiers || [] };
          });
          render();
        }

        function render() {
          const list = document.getElementById('list');
          if (dashboards.length === 0) { list.innerHTML = '<div class="state-msg">لا توجد لوحات منشورة بعد.</div>'; return; }
          list.innerHTML = dashboards.map(d => rowHtml(d.dashboardId || d.id, d.title || d.dashboardId || d.id)).join('');
          dashboards.forEach(d => wireRow(d.dashboardId || d.id));
        }

        function rowHtml(id, title) {
          const s = state[id];
          const everyone = s.mode !== 'restricted';
          const warn = !everyone && s.allowed.length === 0
            ? '<div class="empty-warning">هذه اللوحة مقيّدة ولا تحتوي على أي معرّف مسموح — لن تظهر لأي أحد حتى تضيف واحدًا.</div>' : '';
          return '<div class="dash-row" data-id="' + esc(id) + '">' +
            '<div class="dash-row-head"><span class="dash-title">' + esc(title) + '</span>' +
            '<div class="toggle-group">' +
              '<button type="button" class="toggle-btn everyone-btn' + (everyone ? ' active' : '') + '">للجميع</button>' +
              '<button type="button" class="toggle-btn restricted-btn' + (!everyone ? ' active' : '') + '">مقيّدة</button>' +
            '</div></div>' +
            '<div class="restricted-panel' + (!everyone ? ' open' : '') + '">' +
              '<div class="chip-list"></div>' +
              '<div class="search-row"><input type="text" placeholder="ابحث بالاسم أو أضف يدويًا…" autocomplete="off" /><div class="suggestions" style="display:none"></div></div>' +
              warn +
              '<div style="margin-top:10px"><button type="button" class="toggle-btn save-btn" style="background:var(--accent);color:#fff">حفظ</button><span class="save-note"></span></div>' +
            '</div></div>';
        }

        function wireRow(id) {
          const row = document.querySelector('.dash-row[data-id="' + CSS.escape(id) + '"]');
          const s = state[id];
          const panel = row.querySelector('.restricted-panel');
          const chipList = row.querySelector('.chip-list');

          function renderChips() {
            chipList.innerHTML = s.allowed.map((a, i) =>
              '<span class="chip">' + esc(a.label) + (a.kind ? ' <span class="suggestion-tag">(' + esc(a.kind === 'role' ? 'دور' : 'مستخدم') + ')</span>' : '') +
              '<button type="button" data-i="' + i + '">✕</button></span>').join('');
            chipList.querySelectorAll('button').forEach(btn => btn.addEventListener('click', () => {
              s.allowed.splice(Number(btn.dataset.i), 1);
              renderChips();
              updateWarning();
            }));
          }
          function updateWarning() {
            let warn = panel.querySelector('.empty-warning');
            const shouldWarn = s.mode === 'restricted' && s.allowed.length === 0;
            if (shouldWarn && !warn) {
              warn = document.createElement('div');
              warn.className = 'empty-warning';
              warn.textContent = 'هذه اللوحة مقيّدة ولا تحتوي على أي معرّف مسموح — لن تظهر لأي أحد حتى تضيف واحدًا.';
              panel.querySelector('.search-row').after(warn);
            } else if (!shouldWarn && warn) {
              warn.remove();
            }
          }
          renderChips();

          row.querySelector('.everyone-btn').addEventListener('click', () => {
            s.mode = 'everyone';
            row.querySelector('.everyone-btn').classList.add('active');
            row.querySelector('.restricted-btn').classList.remove('active');
            panel.classList.remove('open');
          });
          row.querySelector('.restricted-btn').addEventListener('click', () => {
            s.mode = 'restricted';
            row.querySelector('.restricted-btn').classList.add('active');
            row.querySelector('.everyone-btn').classList.remove('active');
            panel.classList.add('open');
            updateWarning();
          });

          const input = row.querySelector('.search-row input');
          const suggestions = row.querySelector('.suggestions');
          let searchTimer = null;
          input.addEventListener('input', () => {
            clearTimeout(searchTimer);
            const q = input.value.trim();
            if (!q || !CONFIG.directoryApiUrl) { suggestions.style.display = 'none'; return; }
            searchTimer = setTimeout(async () => {
              try {
                const res = await fetchWithIdentity(CONFIG.directoryApiUrl + '?q=' + encodeURIComponent(q));
                if (!res.ok) throw new Error();
                const results = await res.json();
                const items = Array.isArray(results) ? results : (results.results || []);
                if (!items.length) { suggestions.style.display = 'none'; return; }
                suggestions.innerHTML = items.map((r, i) =>
                  '<div class="suggestion-item" data-i="' + i + '"><span>' + esc(r.label || r.name) + '</span>' +
                  '<span class="suggestion-tag">' + esc(r.kind === 'role' ? 'دور' : 'مستخدم') + '</span></div>').join('');
                suggestions.style.display = 'block';
                suggestions.querySelectorAll('.suggestion-item').forEach(el => el.addEventListener('click', () => {
                  const r = items[Number(el.dataset.i)];
                  s.allowed.push({ id: r.id, label: r.label || r.name, kind: r.kind || 'user' });
                  input.value = '';
                  suggestions.style.display = 'none';
                  renderChips();
                  updateWarning();
                }));
              } catch { suggestions.style.display = 'none'; }
            }, 250);
          });
          // Manual fallback — Directory API absent or the analyst just types a raw identifier
          // and presses Enter, per Part E: "never block on the Directory API's availability."
          input.addEventListener('keydown', e => {
            if (e.key !== 'Enter') return;
            e.preventDefault();
            const value = input.value.trim();
            if (!value) return;
            s.allowed.push({ id: value, label: value, kind: null });
            input.value = '';
            suggestions.style.display = 'none';
            renderChips();
            updateWarning();
          });

          row.querySelector('.save-btn').addEventListener('click', async () => {
            const note = row.querySelector('.save-note');
            if (!CONFIG.permissionsApiUrl) { note.textContent = 'نقطة كتابة الصلاحيات غير مضبوطة.'; return; }
            note.textContent = 'جارٍ الحفظ…';
            try {
              const res = await fetch(CONFIG.permissionsApiUrl, {
                method: 'POST', headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ dashboardId: id, mode: s.mode, allowedIdentifiers: s.allowed }),
              });
              note.textContent = res.ok ? 'تم الحفظ ✓' : 'فشل الحفظ (HTTP ' + res.status + ')';
            } catch (err) {
              note.textContent = 'فشل الحفظ: ' + err.message;
            }
          });
        }

        init();
        </script>
        </body>
        </html>
        """;
    }

    /// <summary>Deliverable 3 — zips up the connector project's embedded source
    /// (Program.cs/.csproj/README.md unchanged; appsettings.json with whatever this integration
    /// already answers pre-filled) so the client can unzip, fill in their own
    /// TargetConnectionString locally, and `dotnet run`. Never includes a connection string or
    /// any other client secret — those never reach this app (see ExternalIntegration's remarks
    /// on ClientDbProvider/ClientSchemaDescription).</summary>
    public byte[] BuildConnectorZip(ExternalIntegration integration)
    {
        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            AddEmbeddedEntry(zip, "connector.Program.cs", "Program.cs");
            AddEmbeddedEntry(zip, "connector.IntegrationConnector.csproj", "IntegrationConnector.csproj");
            AddEmbeddedEntry(zip, "connector.README.md", "README.md");

            var appsettings = ReadEmbeddedText("connector.appsettings.json");
            appsettings = appsettings
                .Replace("\"TargetDbProvider\": \"SqlServer\"", $"\"TargetDbProvider\": \"{(integration.ClientDbProvider is { Length: > 0 } p ? p : "SqlServer")}\"")
                .Replace("\"WriteApiKey\": \"\"", $"\"WriteApiKey\": \"{JsonEscape(integration.ConnectorAuthValue ?? "")}\"")
                .Replace("\"WriteApiAuthHeader\": \"X-Api-Key\"", $"\"WriteApiAuthHeader\": \"{JsonEscape(integration.ConnectorAuthHeader is { Length: > 0 } h ? h : "X-Api-Key")}\"")
                .Replace("\"IdentityParameterName\": \"\"", $"\"IdentityParameterName\": \"{(integration.IdentityConfirmed ? JsonEscape(integration.IdentityParameterName ?? "") : "")}\"");
            var entry = zip.CreateEntry("appsettings.json", CompressionLevel.Optimal);
            using (var writer = new StreamWriter(entry.Open()))
                writer.Write(appsettings);
        }
        return ms.ToArray();
    }

    private static void AddEmbeddedEntry(ZipArchive zip, string resourceName, string entryName)
    {
        var entry = zip.CreateEntry(entryName, CompressionLevel.Optimal);
        using var source = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded connector resource not found: {resourceName}");
        using var target = entry.Open();
        source.CopyTo(target);
    }

    private static string ReadEmbeddedText(string resourceName)
    {
        using var source = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded connector resource not found: {resourceName}");
        using var reader = new StreamReader(source);
        return reader.ReadToEnd();
    }

    private static string JsonEscape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static (string Accent, string Secondary, string Font) ResolveTokens(ExternalIntegration integration) => (
        integration.AccentColor is { Length: > 0 } a ? a : "#2AB37F",
        integration.SecondaryColor is { Length: > 0 } s ? s : "#0B2A22",
        integration.FontFamily is { Length: > 0 } f ? f : "Inter, Tajawal, sans-serif");

    private static string BaseCss((string Accent, string Secondary, string Font) tokens) => $$"""
        :root{--accent:{{tokens.Accent}};--secondary:{{tokens.Secondary}};--ink:#111827;--ink-2:#6B7280;
          --grid:#E5E7EB;--surface:#FFFFFF;--plane:#F9FAFB;--accent-soft:color-mix(in srgb, var(--accent) 14%, white)}
        *{box-sizing:border-box}
        body{margin:0;font-family:{{tokens.Font}};background:var(--plane);color:var(--ink);direction:rtl}
        """;

    /// <summary>Shared by both deliverables — turns the confirmed identity-transport mechanism
    /// into an actual fetchWithIdentity() implementation. Emits a no-op passthrough (plain
    /// fetch, no identity attached) when the integration's transport isn't confirmed yet — a
    /// half-configured integration must never silently start forwarding something, per Part C's
    /// explicit-confirmation requirement.</summary>
    private const string IdentityTransportJs = """
        function fetchWithIdentity(url) {
          const mechanism = CONFIG.identity.mechanism;
          const name = CONFIG.identity.parameterName;
          if (!mechanism || !name) return fetch(url);

          if (mechanism === 'query') {
            const value = new URLSearchParams(location.search).get(name) || '';
            const sep = url.includes('?') ? '&' : '?';
            return fetch(url + sep + encodeURIComponent(name) + '=' + encodeURIComponent(value));
          }
          if (mechanism === 'header') {
            const value = new URLSearchParams(location.search).get(name) || '';
            const headers = {}; headers[name] = value;
            return fetch(url, { headers });
          }
          // 'cookie' — the browser attaches the client-domain cookie automatically; this page
          // never reads document.cookie itself (many auth cookies are httpOnly and JS-inaccessible
          // by design). credentials:'include' just ensures it's actually sent.
          return fetch(url, { credentials: 'include' });
        }
        """;

    // Order matters: & must be escaped first, or escaping < to &lt; right before it would
    // turn that & right back into &amp;lt;.
    private static string Escape(string s) => s.Replace("&", "&amp;").Replace("\"", "&quot;").Replace("<", "&lt;").Replace(">", "&gt;");
}
